version: '3.8'

services:
  # Контейнер с PHP (Laravel)
  app:
    build: .  # Собирает из Dockerfile
    volumes:
      - ./:/var/www/html  # Синхронизация кода Laravel
    ports:
      - "8000:8000"  # Проброс порта для artisan serve
    depends_on:
      - mysql  # Ждёт запуска MySQL
    environment:
      DB_HOST: mysql  # Переменные для Laravel (.env)
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: root
      DB_PASSWORD: secret

  # Контейнер с MySQL
  mysql:
    image: mysql:8.0  # Готовый образ MySQL
    environment:
      MYSQL_ROOT_PASSWORD: secret  # Пароль root
      MYSQL_DATABASE: laravel  # Автоматическое создание БД
    volumes:
      - mysql_data:/var/lib/mysql  # Сохранение данных БД
    ports:
      - "3307:3306"  # Доступ к MySQL с хоста (через 3307)

  # Контейнер с phpMyAdmin (веб-интерфейс для MySQL)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"  # Доступ через http://localhost:8080
    environment:
      PMA_HOST: mysql  # Подключение к MySQL-контейнеру

# Настройки сети и томов
networks:
  laravel_network:  # Сеть для связи контейнеров
volumes:
  mysql_data:  # Постоянное хранилище для MySQL